# .github/workflows/deploy.yml
name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read           # for checking out the repo
  pages: write             # to push to GitHub Pages
  id-token: write          # to mint the deployment token

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      # <-- full history for gh-pages

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
