name: Build & Deploy

# ─ Permissions ──────────────────────────────────────────────────────────────
# Grant just enough rights for Pages to push your build back up to gh‑pages.
permissions:
  contents: read       # we only need to read the repo
  pages: write         # allow writing to gh‑pages
  id-token: write      # (required by peaceiris/actions-gh‑pages@v3)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Disable Jekyll
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
